# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pyqt5\chapter09\testCase\MatrixWinUi.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MatrixWin(object):
    def setupUi(self, MatrixWin):
        MatrixWin.setObjectName("MatrixWin")
        MatrixWin.resize(764, 517)
        self.groupBox_2 = QtWidgets.QGroupBox(MatrixWin)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 701, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.label_4.setObjectName("label_4")
        self.tequilaScrollBar = QtWidgets.QScrollBar(self.groupBox_2)
        self.tequilaScrollBar.setGeometry(QtCore.QRect(110, 20, 311, 20))
        self.tequilaScrollBar.setMaximum(11)
        self.tequilaScrollBar.setProperty("value", 8)
        self.tequilaScrollBar.setSliderPosition(8)
        self.tequilaScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.tequilaScrollBar.setObjectName("tequilaScrollBar")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(540, 20, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(540, 50, 54, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(540, 70, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(540, 110, 54, 12))
        self.label_8.setObjectName("label_8")
        self.tripleSecSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.tripleSecSpinBox.setGeometry(QtCore.QRect(110, 50, 181, 16))
        self.tripleSecSpinBox.setMaximum(11)
        self.tripleSecSpinBox.setProperty("value", 4)
        self.tripleSecSpinBox.setObjectName("tripleSecSpinBox")
        self.limeJuiceLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.limeJuiceLineEdit.setGeometry(QtCore.QRect(110, 80, 181, 16))
        self.limeJuiceLineEdit.setObjectName("limeJuiceLineEdit")
        self.iceHorizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.iceHorizontalSlider.setGeometry(QtCore.QRect(110, 110, 181, 16))
        self.iceHorizontalSlider.setProperty("value", 12)
        self.iceHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.iceHorizontalSlider.setObjectName("iceHorizontalSlider")
        self.selScrollBarLbl = QtWidgets.QLabel(self.groupBox_2)
        self.selScrollBarLbl.setGeometry(QtCore.QRect(460, 22, 54, 20))
        self.selScrollBarLbl.setText("")
        self.selScrollBarLbl.setObjectName("selScrollBarLbl")
        self.selIceSliderLbl = QtWidgets.QLabel(self.groupBox_2)
        self.selIceSliderLbl.setGeometry(QtCore.QRect(460, 110, 54, 20))
        self.selIceSliderLbl.setText("")
        self.selIceSliderLbl.setObjectName("selIceSliderLbl")
        self.groupBox = QtWidgets.QGroupBox(MatrixWin)
        self.groupBox.setGeometry(QtCore.QRect(10, 200, 441, 211))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.speedButton_1 = QtWidgets.QRadioButton(self.groupBox)
        self.speedButton_1.setObjectName("speedButton_1")
        self.speedButtonGroup = QtWidgets.QButtonGroup(MatrixWin)
        self.speedButtonGroup.setObjectName("speedButtonGroup")
        self.speedButtonGroup.addButton(self.speedButton_1)
        self.gridLayout.addWidget(self.speedButton_1, 0, 0, 1, 1)
        self.speedButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.speedButton_4.setObjectName("speedButton_4")
        self.speedButtonGroup.addButton(self.speedButton_4)
        self.gridLayout.addWidget(self.speedButton_4, 1, 0, 1, 1)
        self.speedButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.speedButton_5.setChecked(True)
        self.speedButton_5.setObjectName("speedButton_5")
        self.speedButtonGroup.addButton(self.speedButton_5)
        self.gridLayout.addWidget(self.speedButton_5, 1, 1, 1, 1)
        self.speedButton_6 = QtWidgets.QRadioButton(self.groupBox)
        self.speedButton_6.setObjectName("speedButton_6")
        self.speedButtonGroup.addButton(self.speedButton_6)
        self.gridLayout.addWidget(self.speedButton_6, 1, 2, 1, 1)
        self.speedButton_7 = QtWidgets.QRadioButton(self.groupBox)
        self.speedButton_7.setObjectName("speedButton_7")
        self.speedButtonGroup.addButton(self.speedButton_7)
        self.gridLayout.addWidget(self.speedButton_7, 2, 0, 1, 1)
        self.speedButton_8 = QtWidgets.QRadioButton(self.groupBox)
        self.speedButton_8.setObjectName("speedButton_8")
        self.speedButtonGroup.addButton(self.speedButton_8)
        self.gridLayout.addWidget(self.speedButton_8, 2, 1, 1, 1)
        self.speedButton_9 = QtWidgets.QRadioButton(self.groupBox)
        self.speedButton_9.setObjectName("speedButton_9")
        self.speedButtonGroup.addButton(self.speedButton_9)
        self.gridLayout.addWidget(self.speedButton_9, 2, 2, 1, 1)
        self.speedButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.speedButton_2.setObjectName("speedButton_2")
        self.speedButtonGroup.addButton(self.speedButton_2)
        self.gridLayout.addWidget(self.speedButton_2, 0, 1, 1, 1)
        self.speedButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.speedButton_3.setObjectName("speedButton_3")
        self.speedButtonGroup.addButton(self.speedButton_3)
        self.gridLayout.addWidget(self.speedButton_3, 0, 2, 1, 1)
        self.resultGroup = QtWidgets.QGroupBox(MatrixWin)
        self.resultGroup.setGeometry(QtCore.QRect(470, 200, 241, 211))
        self.resultGroup.setObjectName("resultGroup")
        self.resultText = QtWidgets.QTextEdit(self.resultGroup)
        self.resultText.setGeometry(QtCore.QRect(10, 20, 221, 181))
        self.resultText.setObjectName("resultText")
        self.layoutWidget = QtWidgets.QWidget(MatrixWin)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 440, 341, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout.addWidget(self.okBtn)
        self.clearBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.clearBtn.setObjectName("clearBtn")
        self.horizontalLayout.addWidget(self.clearBtn)
        self.cancelBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)

        self.retranslateUi(MatrixWin)
        self.tequilaScrollBar.valueChanged['int'].connect(MatrixWin.uiScrollBarValueChanged)
        self.iceHorizontalSlider.valueChanged['int'].connect(MatrixWin.uiIceSliderValueChanged)
        self.okBtn.clicked.connect(MatrixWin.uiAccept)
        self.clearBtn.clicked.connect(MatrixWin.uiClear)
        self.cancelBtn.clicked.connect(MatrixWin.uiReject)
        QtCore.QMetaObject.connectSlotsByName(MatrixWin)

    def retranslateUi(self, MatrixWin):
        _translate = QtCore.QCoreApplication.translate
        MatrixWin.setWindowTitle(_translate("MatrixWin", "玛格丽特鸡尾酒*调酒器"))
        self.groupBox_2.setTitle(_translate("MatrixWin", "原料"))
        self.label.setText(_translate("MatrixWin", "龙舌兰酒"))
        self.label_2.setText(_translate("MatrixWin", "三重蒸馏酒"))
        self.label_3.setText(_translate("MatrixWin", "柠檬汁"))
        self.label_4.setText(_translate("MatrixWin", "冰块"))
        self.label_5.setText(_translate("MatrixWin", "升"))
        self.label_6.setText(_translate("MatrixWin", "升"))
        self.label_7.setText(_translate("MatrixWin", "升"))
        self.label_8.setText(_translate("MatrixWin", "个"))
        self.limeJuiceLineEdit.setText(_translate("MatrixWin", "12.0"))
        self.groupBox.setTitle(_translate("MatrixWin", "9种搅拌速度"))
        self.speedButton_1.setText(_translate("MatrixWin", "&Mix"))
        self.speedButton_4.setText(_translate("MatrixWin", "&Chop"))
        self.speedButton_5.setText(_translate("MatrixWin", "&Karate Chop"))
        self.speedButton_6.setText(_translate("MatrixWin", "&Beat"))
        self.speedButton_7.setText(_translate("MatrixWin", "&Smash"))
        self.speedButton_8.setText(_translate("MatrixWin", "&Liquefy"))
        self.speedButton_9.setText(_translate("MatrixWin", "&Vaporize"))
        self.speedButton_2.setText(_translate("MatrixWin", "&Whip"))
        self.speedButton_3.setText(_translate("MatrixWin", "&Puree"))
        self.resultGroup.setTitle(_translate("MatrixWin", "操作结果"))
        self.okBtn.setText(_translate("MatrixWin", "OK"))
        self.clearBtn.setText(_translate("MatrixWin", "Clear"))
        self.cancelBtn.setText(_translate("MatrixWin", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MatrixWin = QtWidgets.QWidget()
    ui = Ui_MatrixWin()
    ui.setupUi(MatrixWin)
    MatrixWin.show()
    sys.exit(app.exec_())

